### ISSUE TITLE
updateDecoder no longer works

### ISSUE THREAD

**Issue by lechium** [hoyois/clicktoplugin#158]
there is a new base.js file and the updateDecoder function in Youtube.js killer dies on this line specifically

var index = xhr2.responseText.indexOf(";var " + /^[$_A-Za-z0-9]+/.exec(match[1])[0] + "=\{"); with this error

[Error] TypeError: null is not an object (evaluating '/^[$_A-Za-z0-9]+/.exec(match[1])')
	(anonymous function)

the new base.js file is here http://s.ytimg.com/yts/jsbin/player-en_US-vflXJM_5_/base.js

**Comment by hoyois** [comment]
Already fixed here: https://raw.githubusercontent.com/hoyois/plugin-to-html5/master/YouTube.js
BTW, this variant is immune to these changes: https://raw.githubusercontent.com/hoyois/plugin-to-html5/master/YouTubeXHR.js (although it has other disadvantages).

**Comment by hoyois** [comment]
Fixed in v3.2.

**Comment by schmandforke** [comment]
still getting black youtube screen, do i miss something ? running ClickToPlugin 3.2 stable
